version: "3.3"

services:
  bookstore-app:
    container_name: bookstore-app
    build: 
      context: .
      dockerfile: ./docker/dev/app.dockerfile
    restart: always
    ports:
      - 5173:5173
      - 5555:5555
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD-password}@bookstore-db:${DB_PORT-5432}/postgres
      - JWT_SECRET=${JWT_SECRET-secret}
      - PROD=${PROD-false}
  bookstore-db:
    container_name: bookstore-db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD-password}
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT-5432}:5432