version: "3.3"

services:
  bookstore-app:
    container_name: bookstore-app
    build: 
      context: .
      dockerfile: ./docker/dev/app.dockerfile
    restart: always
    ports:
      - 5173:5173
    volumes:
      - ./app:/app
  bookstore-db:
    container_name: bookstore-db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD-password}
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT-5432}:5432