version: "3.3"

services:
  bookstore-app:
    container_name: bookstore-app
    build: 
      context: .
      dockerfile: ./docker/prod/app.dockerfile
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./app:/app
    environment:
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD:?password missing}@bookstore-db:5432/postgres
      JWT_SECRET: ${JWT_SECRET:?JWT SECRET REQUIRED}
      PROD: ${PROD:?PROD PARAM REQUIRED}
      APP_PORT: ${APP_PORT}
      NOT_VERCEL: true
  bookstore-db:
    container_name: bookstore-db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:?DB PASSWORD REQUIRED}
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT:?MUST SET DB PORT}:5432
      