version: "3.3"

services:
  bookstore-app:
    container_name: bookstore-app
    build: 
      context: .
      dockerfile: ./docker/prod/app.dockerfile
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./app:/app
    environment:
      APP_PORT: ${APP_PORT}